### ISSUE TITLE
overloading functions Use `Base.:*` or import this operator in current file

### ISSUE THREAD

**Issue by Roger-luo** [jrevels/YASGuide#5]
I notice a lot Julia package use

```julia
Base.:*(a, b) = # blabla
```

syntax instead of import an operator at the upper most file with a lot `include`s, e.g

```julia
# Foo.jl

module Foo

import Base: *, +, ==

include("A.jl")
include("B.jl")

end
```

I think overloading functions explicitly with their module name is better because this will avoid potential error caused by copy-pasting/moving files. So maybe the following rules can be added:

- explicitly `ModuleName.FunctionName` to overload functions in other module, or import the function name you intended to overload in each file

**Comment by jrevels** [comment]
resolved in #6
