### ISSUE TITLE
indent of macro begin <expr> end

### ISSUE THREAD

**Issue by Roger-luo** [jrevels/YASGuide#7]
This happens in a lot places, e.g unit tests

Which is preferred?

- 4 space indent

code inside `begin ... end` is a sub-block of the `begin ... end` block, seems to make sense as well.

```julia
@testset "test blabla" begin
    # 4 space indent
end
```

- no indent

Code in side begin end are executed in `begin ... end`'s scope, so this make sense 

```julia
@testset "test blabla" begin
# no indent
end
```

**Comment by jrevels** [comment]
The indent is definitely preferred here. I can see that being annoying for really long testsets, but maybe that just means overlong testsets should be broken up/use an `include` instead.

Hmm, what about adding these rules:

- `keyword...end` statements form "code blocks" if the delimiting terms (`keyword` and `end`) are on separate lines. The contents of such code blocks should be indented.
- In code blocks formed by `keyword...end` statements, the `end` should either be on the same line as `keyword`, or on its own line (i.e. no code block content should precede the `end`). In other words, this is bad:
```julia
function f(x)
    return g(x, 1) end
```

while this is good:

```julia
function f(x)
    return g(x, 1) 
end
```

**Comment by Roger-luo** [comment]
So you mean it should always indent? make sense to me.
